name: conda-pybkb-311
channels:
  - pytorch
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.11.*  # or don't specify the version and use the latest stable Python
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.*  # or 1.1.*, or no version at all -- as you want
  - cpuonly
  - pytorch::pytorch=2.0.1
  - pytorch::torchaudio=2.0.2
  - pytorch::torchvision=0.15.2
  - pip:
      - apricot-select==0.6.1 # Need for pomegranate
      - joblib==1.3.1 # Needed for pomegranate
      - llvmlite==0.40.1 # Needed for pomegranate
      - nose==1.3.7 # Needed for pomegranate
      - numba==0.57.1 # Needed for pomegranate
      - numpy==1.24.4 # Needed for pomegranate
      - scikit-learn==1.3.0 # Needed for pomegranate
      - scipy==1.11.1 # Needed for pomegrantate
      - threadpoolctl==3.1.0 # Needed for pomegranate
      - pomegranate==1.0.0
      - gurobipy==10.0.2 # Poetry can't find install candidate, so installing here.

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
